### ISSUE TITLE
第十二課と第十三課

### ISSUE THREAD

**Issue by Serashiki** [Frederick-S/JapaneseNotes#4]
**第十二課**

称呼别人的姐姐：お姉さん (*おねえさｎ*)
和自己的姐姐说话：お姉さん (*おねえさｎ*)

→ おねえさん

**第十三課**

アニメ：*动漫*

→ 私が思うですが、アニメは「动漫」ではなく、「動画」です。

19. だいたい

(*だいたい*)　→ ここ、漢字を書くつもりではないでしょうか。^^

**Comment by Frederick-S** [comment]
Fixed. Thanks!
