### ISSUE TITLE
第六课

### ISSUE THREAD

**Issue by ykchong45** [Frederick-S/JapaneseNotes#7]
[第六课](http://frederick-s.github.io/JapaneseNotes/%E5%88%9D%E7%BA%A7/%E7%AC%AC%E4%BA%8C%E5%8D%95%E5%85%83/%E7%AC%AC%E5%85%AD%E8%AF%BE.html)日历部分
10号：とおか。
原文里写为：よおか

**Comment by Frederick-S** [comment]
> [第六课](http://frederick-s.github.io/JapaneseNotes/%E5%88%9D%E7%BA%A7/%E7%AC%AC%E4%BA%8C%E5%8D%95%E5%85%83/%E7%AC%AC%E5%85%AD%E8%AF%BE.html)日历部分
> 10号：とおか。
> 原文里写为：よおか

感谢指正，已更新。
